sudo: required

services:
- docker

env:
  - DOCKER_VERSION=1.11.0-0~trusty

before_install:
  - apt-cache madison docker-engine
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - docker version


script:
  - docker build .
